"""Added wind speed and humidity columns

Revision ID: 4560d2185982
Revises: 15c4e88bec4a
Create Date: 2024-07-24 12:21:03.105257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4560d2185982'
down_revision = '15c4e88bec4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather', schema=None) as batch_op:
        batch_op.add_column(sa.Column('humidity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wind_speed', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather', schema=None) as batch_op:
        batch_op.drop_column('wind_speed')
        batch_op.drop_column('humidity')

    # ### end Alembic commands ###
