"""Added new columns to history table

Revision ID: 973c0ee63846
Revises: c88588bbe2da
Create Date: 2024-07-12 10:26:08.926728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973c0ee63846'
down_revision = 'c88588bbe2da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_weather', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_time', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_weather', schema=None) as batch_op:
        batch_op.drop_column('local_time')

    # ### end Alembic commands ###
