"""initial migration

Revision ID: c88588bbe2da
Revises: 
Create Date: 2024-07-09 15:46:21.511283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c88588bbe2da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historical_weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.Column('weather_icon', sa.String(length=50), nullable=False),
    sa.Column('low_temperature', sa.Float(), nullable=False),
    sa.Column('high_temperature', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.Column('local_time', sa.String(length=50), nullable=False),
    sa.Column('weather_icon', sa.String(length=50), nullable=False),
    sa.Column('low_temperature', sa.Float(), nullable=False),
    sa.Column('high_temperature', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    op.drop_table('historical_weather')
    op.drop_table('favorite_location')
    # ### end Alembic commands ###
